name: warehouse-sync
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  sync-gitee:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@master
      - name: Sync Gitee
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:sg996/sg996.github.io.git
          destination-repo: git@gitee.com:sg996/sg996.git
